language: go
go:
- 1.9.2

services:
 - docker

before_install:
- docker-compose up -d
- ./vagrant/run_toxiproxy.sh

env:
  global:
    - KAFKA_PEERS=localhost:9092
    - TOXIPROXY_ADDR=localhost:8474
    - DEBUG=true

install:
- make install_dependencies

script:
- make test

sudo: true
